# -*- coding:utf-8 -*-
from configparser import RawConfigParser
from traceback import format_exc

from Classes.Static.Const import Const

try:
    print('>>正在重写ini文件...')
    config_settings = RawConfigParser()
    config_settings.add_section(Const.NODE_FORMULA)
    config_settings.set(Const.NODE_FORMULA, Const.NEED_ACTORS_END_OF_TITLE, "否")
    config_settings.add_section(Const.NODE_NFO)
    config_settings.set(Const.NODE_NFO, Const.NEED_NFO, "是")
    config_settings.set(Const.NODE_NFO, Const.NAME_NFO_TITLE_FORMULA, "车牌+空格+标题")
    config_settings.set(Const.NODE_NFO, Const.NEED_ZH_PLOT, "否")
    config_settings.set(Const.NODE_NFO, "plot是否写入javlibrary的热评？", "否")
    config_settings.set(Const.NODE_NFO, Const.EXTRA_GENRES, "系列、片商")
    config_settings.set(Const.NODE_NFO, Const.NEED_NFO_GENRES, "是")
    config_settings.set(Const.NODE_NFO, Const.NEED_NFO_TAGS, "是")
    config_settings.add_section(Const.NODE_VIDEO)
    config_settings.set(Const.NODE_VIDEO, Const.NEED_RENAME_VIDEO, "是")
    config_settings.set(Const.NODE_VIDEO, Const.NAME_VIDEO_FORMULA, "车牌+空格+标题")
    config_settings.add_section(Const.NODE_FOLDER)
    config_settings.set(Const.NODE_FOLDER, Const.NEED_RENAME_FOLDER, "是")
    config_settings.set(Const.NODE_FOLDER, Const.NAME_FOLDER_FORMULA, "【+全部演员+】+车牌")
    config_settings.add_section(Const.NODE_CLASSIFY)
    config_settings.set(Const.NODE_CLASSIFY, Const.NEED_CLASSIFY, "否")
    config_settings.set(Const.NODE_CLASSIFY, Const.NEED_CLASSIFY_FOLDER, "文件夹")
    config_settings.set(Const.NODE_CLASSIFY, Const.DIR_CUSTOM_CLASSIFY_TARGET, "所选文件夹")
    config_settings.set(Const.NODE_CLASSIFY, Const.CLASSIFY_FORMULA, "车牌前缀\全部演员")
    config_settings.add_section(Const.NODE_FANART)
    config_settings.set(Const.NODE_FANART, Const.NEED_DOWNLOAD_FANART, "是")
    config_settings.set(Const.NODE_FANART, Const.NAME_FANART_FORMULA, "视频+-fanart.jpg")
    config_settings.set(Const.NODE_FANART, Const.NAME_POSTER_FORMULA, "视频+-poster.jpg")
    config_settings.set(Const.NODE_FANART, Const.NEED_SUBTITLE_WATERMARK, "否")
    config_settings.set(Const.NODE_FANART, Const.NEED_DIVULGE_WATERMARK, "否")
    config_settings.add_section(Const.NODE_SUBTITLE)
    config_settings.set(Const.NODE_SUBTITLE, Const.NEED_RENAME_SUBTITLE, "是")
    config_settings.set(Const.NODE_SUBTITLE, "是否在收集字幕时跳过已有字幕的影片？", "是")
    config_settings.add_section(Const.NODE_KODI)
    config_settings.set(Const.NODE_KODI, Const.NEED_ACTOR_SCULPTURE, "否")
    config_settings.set(Const.NODE_KODI, Const.NEED_ONLY_CD, "否")
    config_settings.add_section("emby/jellyfin专用")
    config_settings.set("emby/jellyfin专用", "网址", "http://localhost:8096/")
    config_settings.set("emby/jellyfin专用", "API ID", "b55d950becc74bbebbf4698d995db826")
    config_settings.set("emby/jellyfin专用", "是否覆盖以前上传的头像？", "否")
    config_settings.add_section(Const.NODE_PROXY)
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY, "否")
    config_settings.set(Const.NODE_PROXY, Const.NEED_HTTP_OR_SOCKS5, "http")
    config_settings.set(Const.NODE_PROXY, Const.PROXY, "127.0.0.1:10809")
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY_LIBRARY, "否")
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY_BUS, "否")
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY_321, "否")
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY_DB, "否")
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY_ARZON, "否")
    config_settings.set(Const.NODE_PROXY, Const.NEED_PROXY_DMM, "否")
    # config_settings.set(NODE_OTHER, "是否将全部演员（多个）表现为“n人共演？", "否")
    config_settings.add_section(Const.NODE_FILE)
    config_settings.set(Const.NODE_FILE, Const.SURPLUS_WORDS_IN_YOUMA_SUREN, "xhd1080、mm616、fhd-1080")
    config_settings.set(Const.NODE_FILE, Const.SURPLUS_WORDS_IN_WUMA,
                        "1080p、caribbean、carib、1pondo、1pon、fhd、all、tokyo-hot、tokyohot、3xplanet、full")
    config_settings.set(Const.NODE_FILE, Const.SUBTITLE_SYMBOL_WORDS, "-C、_C、中字、中文字幕、字幕")
    config_settings.set(Const.NODE_FILE, Const.SUBTITLE_EXPRESSION, "㊥")
    config_settings.set(Const.NODE_FILE, Const.DIVULGE_SYMBOL_WORDS, "流出")
    config_settings.set(Const.NODE_FILE, Const.DIVULGE_EXPRESSION, "无码流出")
    config_settings.set(Const.NODE_FILE, "有码", "有码")
    config_settings.set(Const.NODE_FILE, "无码", "无码")
    config_settings.set(Const.NODE_FILE, "素人", "素人")
    config_settings.set(Const.NODE_FILE, "FC2", "FC2")
    config_settings.add_section(Const.NODE_OTHER)
    config_settings.set(Const.NODE_OTHER, Const.LANGUAGE, "简")
    config_settings.set(Const.NODE_OTHER, Const.URL_LIBRARY, "https://www.javlibrary.com/")
    config_settings.set(Const.NODE_OTHER, Const.URL_BUS, "https://www.seejav.bid")
    config_settings.set(Const.NODE_OTHER, Const.URL_DB, "https://javdb36.com/")
    config_settings.set(Const.NODE_OTHER, Const.DB_CF_CLEARANCE,
                        "1ngSctnWLzFKPN1Hn87HQPnARi5sWQM9llVtarUPAsM-1644029815-0-150")
    config_settings.set(Const.NODE_OTHER, Const.LIBRARY_CF_CLEARANCE,
                        "biyj49Wyi8FEOKojC.brqWsnLxuGxM8AcTLTJJ71xQ0-1648358264-0-150")
    config_settings.set(Const.NODE_OTHER, Const.ARZON_PHPSESSID, "679fpv1fgl9vjoeuo36q8crre7")
    config_settings.set(Const.NODE_OTHER, Const.TUPLE_VIDEO_TYPES, "mp4、mkv、avi、wmv、iso、rmvb、flv、ts")
    config_settings.set(Const.NODE_OTHER, Const.INT_TITLE_LEN, "50")
    config_settings.add_section(Const.NODE_TRAN)
    config_settings.set(Const.NODE_TRAN, Const.TRAN_ID, "")
    config_settings.set(Const.NODE_TRAN, Const.TRAN_SK, "")
    config_settings.add_section(Const.NODE_BODY)
    config_settings.set(Const.NODE_BODY, Const.NEED_FACE, "否")
    config_settings.set(Const.NODE_BODY, Const.AI_ID, "")
    config_settings.set(Const.NODE_BODY, Const.AI_AK, "")
    config_settings.set(Const.NODE_BODY, Const.AI_SK, "")
    config_settings.write(open(Const.INI, "w", encoding='utf-8-sig'))
    print(f'    >“{Const.INI}”重写成功！')
    ####################################################################################################################
    config_actor = RawConfigParser()
    config_actor.add_section("缺失的演员头像")
    config_actor.set("缺失的演员头像", "演员姓名", "N(次数)")
    config_actor.add_section("说明")
    config_actor.set("说明", "上面的“演员姓名 = N(次数)”的表达式", "后面的N数字表示你有N部(次)影片都在找她的头像，可惜找不到")
    config_actor.set("说明", "你可以去保存一下她的头像jpg到“演员头像”文件夹", "以后就能保存她的头像到影片的文件夹了")
    config_actor.write(open(Const.INI_ACTOR, "w", encoding='utf-8-sig'))
    print('    >“actors_for_kodi.ini”重写成功！')
    input('>>结束!')
except:
    print(format_exc())
    input('\n创建ini失败，解决上述问题后，重新打开exe创建ini！')
